import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { CalendarDays, X } from "lucide-react";
import { services } from "../../data/services";
import { getCustomer } from "../../utils/authMock";
import { loadMock, saveMock, uid } from "../../utils/prototypeStore";
import "../../styles/ecommerce/pages.css";

export default function ServicesPage(){const nav=useNavigate();const [selected,setSelected]=useState(null);const start=service=>{if(!getCustomer()){sessionStorage.setItem("av_pending_action",JSON.stringify({type:"book_service",service:service.id}));nav("/login");return}setSelected(service)};return <section className="page-shell"><div className="container"><div className="page-intro"><div><div className="eyebrow">Services</div><h1 className="page-title">Professional aircon service</h1><p className="section-copy">Installation, maintenance, repair, troubleshooting, and urgent service with a clear booking flow on every device.</p></div></div><div className="services-list-grid">{services.map(service=>{const Icon=service.icon;return <article className="surface service-list-card" key={service.id}><Icon size={30}/><h2>{service.name}</h2><p>{service.desc}</p><button className="btn btn-dark" onClick={()=>start(service)}>Book Service</button></article>})}</div></div>{selected&&<BookingDialog service={selected} onClose={()=>setSelected(null)}/>}</section>}

function BookingDialog({service,onClose}){const customer=getCustomer();const [form,setForm]=useState({date:"",time:"09:00",address:"Calamba, Laguna",concern:"",notes:""});const set=(k,v)=>setForm(f=>({...f,[k]:v}));const submit=()=>{if(!form.date||!form.address){alert("Please enter a preferred date and service address.");return}const items=loadMock("av_customer_services",[]);const record={id:uid("SR"),service:service.name,schedule:`${form.date} · ${form.time}`,address:form.address,concern:form.concern,notes:form.notes,status:"Pending Approval",customer:customer?.name||"Customer"};saveMock("av_customer_services",[record,...items]);alert(`Service request ${record.id} submitted.`);onClose()};return <div className="service-booking-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="service-booking-dialog"><div className="service-booking-head"><div><span>Service Booking</span><h2>{service.name}</h2></div><button onClick={onClose}><X size={18}/></button></div><div className="service-booking-grid"><label>Preferred date<input className="form-control" type="date" value={form.date} onChange={e=>set("date",e.target.value)}/></label><label>Preferred time<input className="form-control" type="time" value={form.time} onChange={e=>set("time",e.target.value)}/></label><label className="full">Service address<input className="form-control" value={form.address} onChange={e=>set("address",e.target.value)}/></label><label className="full">Concern<textarea className="form-control" rows="3" value={form.concern} onChange={e=>set("concern",e.target.value)} placeholder="Example: unit is not cooling properly"/></label><label className="full">Notes<textarea className="form-control" rows="2" value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><div className="service-booking-actions"><button className="btn btn-soft" onClick={onClose}>Cancel</button><button className="btn btn-dark" onClick={submit}><CalendarDays size={16}/> Submit Request</button></div></section></div>}
