import { useEffect, useMemo, useState } from "react";
import { Eye, Search, X, CheckCircle2 } from "lucide-react";
import { orders as seedOrders } from "../../data/mockManagement";
import { getPosOrders } from "../../utils/managementStore";
import { loadMock, saveMock } from "../../utils/prototypeStore";

const KEY="av_managed_orders";
const money=v=>`₱${Number(v||0).toLocaleString("en-PH")}`;
const statusClass=s=>{const v=String(s||"").toLowerCase();if(v.includes("complete")||v.includes("delivered")||v.includes("ready"))return"success";if(v.includes("pending")||v.includes("processing"))return"warning";if(v.includes("cancel")||v.includes("failed"))return"danger";return"info"};
const nextStatus=order=>{const pickup=["Processing","Ready for Pickup","Picked Up","Completed"];const delivery=["Pending Payment","Processing","Out for Delivery","Delivered","Completed"];const flow=String(order.type).toLowerCase().includes("pickup")?pickup:delivery;const i=flow.indexOf(order.status);return flow[Math.min(i<0?1:i+1,flow.length-1)]};

export default function OrdersPage(){
 const [posOrders,setPosOrders]=useState(()=>getPosOrders()); const [seed,setSeed]=useState(()=>loadMock(KEY,seedOrders)); const [search,setSearch]=useState(""); const [selected,setSelected]=useState(null);
 useEffect(()=>{const refresh=()=>setPosOrders(getPosOrders());window.addEventListener("av-management-updated",refresh);window.addEventListener("storage",refresh);return()=>{window.removeEventListener("av-management-updated",refresh);window.removeEventListener("storage",refresh)}},[]);
 const all=useMemo(()=>[...posOrders,...seed],[posOrders,seed]); const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return !q?all:all.filter(o=>Object.values(o).join(" ").toLowerCase().includes(q))},[all,search]);
 const advance=order=>{if(order.source==="POS")return;const next=seed.map(x=>x.id===order.id?{...x,status:nextStatus(x)}:x);setSeed(next);saveMock(KEY,next)};
 return <><div className="mgmt-page-head"><div><h1>Orders</h1><p>Process online, pickup, delivery, service, and cashier-created walk-in orders in one queue.</p></div></div><section className="mgmt-panel"><div className="mgmt-panel-header orders-toolbar"><div><h2>All Orders</h2><span className="badge badge-blue">{all.length} records</span></div><label className="mgmt-search-box"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search order, customer, source..."/></label></div><div className="responsive-table"><table><thead><tr><th>ID</th><th>Customer</th><th>Source</th><th>Type</th><th>Status</th><th>Payment</th><th>Total</th><th>Actions</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id}><td data-label="Order"><span className="table-primary">{o.id}</span><span className="table-secondary">{o.createdAt||"Mock order"}</span></td><td data-label="Customer">{o.customer}</td><td data-label="Source"><span className="status-pill info">{o.source||"Online"}</span></td><td data-label="Type">{o.type}</td><td data-label="Status"><span className={`status-pill ${statusClass(o.status)}`}>{o.status}</span></td><td data-label="Payment">{o.paymentMethod?`${o.payment} · ${o.paymentMethod}`:o.payment}</td><td data-label="Total"><strong>{money(o.total)}</strong></td><td data-label="Actions"><div className="action-row"><button title="View" onClick={()=>setSelected(o)}><Eye/></button>{o.source!=="POS"&&o.status!=="Completed"&&<button className="action-primary" title="Advance order status" onClick={()=>advance(o)}><CheckCircle2/></button>}</div></td></tr>)}</tbody></table></div></section>{selected&&<div className="mgmt-dialog-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section className="mgmt-dialog"><div className="mgmt-dialog-head"><div><span>Order Details</span><h2>{selected.id}</h2></div><button onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="order-detail-grid"><div><span>Customer</span><strong>{selected.customer}</strong></div><div><span>Source</span><strong>{selected.source||"Online"}</strong></div><div><span>Type</span><strong>{selected.type}</strong></div><div><span>Status</span><strong>{selected.status}</strong></div><div><span>Payment</span><strong>{selected.paymentMethod||selected.payment}</strong></div><div><span>Total</span><strong>{money(selected.total)}</strong></div></div>{selected.items?.length?<div className="order-detail-items"><h3>Items</h3>{selected.items.map(item=><div key={item.key}><span>{item.qty} × {item.name} {item.detail?`· ${item.detail}`:""}</span><strong>{money(item.price*item.qty)}</strong></div>)}</div>:<p className="muted">Example seeded order. Detailed line items can be added later from the backend.</p>}</section></div>}</>
}
